### ISSUE TITLE
RequireParentheses enhancement

### ISSUE THREAD

**Issue by mockdeep** [bbatsov/rubocop#1045]
We're running into some inconsistencies in our codebase in terms of where to put parentheses, and I thought it might be nice to have a rubocop rule to dictate this. I saw [this discussion](https://github.com/bbatsov/rubocop/issues/714#issuecomment-31516997), and I think I have an approach that would be tenable, at least for our case. Basically, parentheses are required globally with a whitelist of exceptions in `rubocop.yml`, in which case they _should not_ have parens. Something like:

```yaml
RequireParentheses:
  RequireNoParens:
    - has_many
    - attr_accessible
    - attr_accessor
    - to
    - to_not
    - not_to
    - click_button
```

The only issue is that the whitelist might get a bit lengthy...

**Comment by bbatsov** [comment]
Seems we won't be implementing this after all as we didn't come up with a sensible way to do so.

**Comment by adsteel** [comment]
FWIW, after adding a well configured rubocop to a new project, this is probably the issue I waste the most time addressing with other folks. I'd love to see the issue stay open at least.

**Comment by alexdowad** [comment]
> I'd love to see the issue stay open at least.

If you have a proposal on how to improve the situation, maybe you could open a new issue?

**Comment by adsteel** [comment]
@alexdowad I thought issues were for problems, and their conversations were for possible solutions?

**Comment by techpeace** [comment]
If you're dealing with this in RSpec source files, you can always exclude those files from that cop as a workaround:

```yaml
# Ignore absence of method call parentheses in RSpec.
Style/MethodCallWithArgsParentheses:
  Exclude:
    - spec/**/*.rb
```
