### ISSUE TITLE
Include/Exclude files for every RailsCops

### ISSUE THREAD

**Issue by yous** [bbatsov/rubocop#1246]
Like `AllCops`, I want to include/exclude some files for `Rails/*` cops. In my project, there are an rails app and another app which is not using whole rails but part of it. I want to use RuboCop for these two apps, but use Rails cops only for rails app.

May be the `.rubocop.yml` would be:
``` yml
AllCops:
  RunRailsCops: true
  AllRailsCops:
    Exclude:
      - 'another_app/**/*'
```

or with separated `AllRailsCops`:
``` yml
AllCops:
  RunRailsCops: true

AllRailsCops:
  Exclude:
    - 'another_app/**/*'
```
