### ISSUE TITLE
Change the way rubocop thinks about heredocs?

### ISSUE THREAD

**Issue by jfelchner** [bbatsov/rubocop#1407]
I was about to put in a request to have the LineLength cop ignore heredocs and, when I searched old issues, I realized there seems to be a bit of a theme.

It seems people have issues with heredocs when rubocop tries to style them.  Typically you use heredocs for preformatted text.  Preformatted text which may or may not exceed line length.  Preformatted text which may or may not be representing Ruby.

I don't really care about syntax within my heredocs in general and considering a lot of heredocs are representations of other languages (eg SQL, YAML, JavaScript, etc), rubocop doesn't exactly play a part in those.

Additionally there are *many* places in the code which are doing heredoc-specific logic.  It seems ripe for extraction.

I felt like a discussion may be in order to think about how else we might construct the cops to work with heredocs.

#### Heredoc Key Whitelist

Specifies the allowable keys to use in heredocs.  Example:

```yaml
Style/HeredocKey:
  Whitelist:
    - HEREDOC
    - SQL
    - RUBY
    - TEXT
    - CONTENTS
```

```ruby
my_heredoc = <<-HERDOC
  Here's my Heredoc
HERDOC
```

The above would cause an error.

#### Heredoc Configuration Mixin

The Heredoc configuration mixin would enable cops to perform special behavior when they encounter a heredoc.  Example:

```yaml
Metrics/LineLength:
  Heredocs:
    ExcludeKeys:
      - SQL
      - TEXT
      - XML
```

```yaml
Metrics/LineLength:
  Heredocs:
    Exclude: true
```

Aaaaaaaaaaaaaaand GO :crossed_flags: :runner:
