### ISSUE TITLE
Don't enforce cops after `__END__`

### ISSUE THREAD

**Issue by lloeki** [bbatsov/rubocop#1541]
`__END__` can be used to mark the end of a Ruby file, and the remainder can be used as raw data. Homebrew uses this to include simple patches straight inside its formulas.

**Comment by bbatsov** [comment]
I'm not sure RuboCop should handle this or `parser`. @whitequark what do you think? Perhaps parser should simply ignore code after `__END__`.

**Comment by whitequark** [comment]
Parser ignores code after `__END__`.

```
$ ruby-parse -e $'foo\n__END__\nbar'
(send nil :foo)
```

**Comment by jonas054** [comment]
I think the only cops that have a problem with `__END__` are the ones that examine code line-by-line:
* Metrics/LineLength
* Style/EndOfLine
* Style/CommentIndentation
* Style/Tab
* Style/TrailingWhitespace

Does that sound about right, @lloeki, or did you run into problems with other cops?

**Comment by bbatsov** [comment]
Yeah, you're probably right.

**Comment by lloeki** [comment]
Those are the ones I encountered:

```yaml
Style/TrailingWhitespace:
    Enabled: false
Style/Tab:
    Enabled: false
Style/TrailingBlankLines:
    Enabled: false
```
