### ISSUE TITLE
Style/TrivialAccessors doesn't differentiate the method name and variable accessed

### ISSUE THREAD

**Issue by zenspider** [bbatsov/rubocop#1605]
Sometimes they're non-trivial:

```ruby
    def name
      @NAME
    end
```

**Comment by Koronen** [comment]
I have also run into this issue a couple of times and would appreciate supporting this differentiation. :+1:

**Comment by bbatsov** [comment]
We have a config option for this. Have a look [here](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L494).

**Comment by Koronen** [comment]
Great. Thanks @bbatsov!

**Comment by zenspider** [comment]
Nope. Doesn't seem to work. Please reopen:

```yaml
Style/TrivialAccessors:              # bug: https://github.com/bbatsov/rubocop/issues/1604
  ExactNameMatch: false
  Enabled: true                      # bug: https://github.com/bbatsov/rubocop/issues/1605
```

vs:

```ruby
    def name
      @NAME
    end

    def name= o
      @NAME = o
    end
```

**Comment by Koronen** [comment]
`ExactNameMatch: false` is the default. Changing it to `ExactNameMatch: true` should stop `Style/TrivialAccessors` from complaining in RuboCop v0.28.0.
```yml
# rubocop.yml
Style/TrivialAccessors:
  ExactNameMatch: true
  Enabled: true
```
```ruby
# name.rb
    def name
      @NAME
    end

    def name= o
      @NAME = o
    end
```
```sh
rubocop -c rubocop.yml --only Style/TrivialAccessors name.rb
```
