### ISSUE TITLE
Style/ClassAndModuleChildren EnforcedStyle compact is not smart

### ISSUE THREAD

**Issue by zenspider** [bbatsov/rubocop#1606]
It reports top level modules as non-compliant?!?

```ruby
module Minitest
end
```

**Comment by Koronen** [comment]
What version of RuboCop are you using? I tried reproducing this error using RuboCop v0.28.0 and the files below, but I don't see any reported offences. Am I missing something?
```yml
# rubocop.yml
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
```
```ruby
# minitest.rb
module Minitest
end
```
```sh
rubocop -c rubocop.yml --only Style/ClassAndModuleChildren minitest.rb
```

**Comment by zenspider** [comment]
Sorry. Maybe I stripped it too much? Try the actual minitest code: `rubocop $(dirname $(gem which minitest))`

`0.28.0 (using Parser 2.2.0.2, running on ruby 2.0.0 universal.x86_64-darwin14)`

**Comment by Koronen** [comment]
The following seems to be a minimal example.
```yml
# rubocop.yml
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
```
```ruby
# minitest.rb
module Minitest
  module Assertions
  end
end
```
```
$ rubocop -c rubocop.yml --only Style/ClassAndModuleChildren minitest.rb
Inspecting 1 file
C

Offenses:

minitest.rb:1:8: C: Use compact module/class definition instead of nested style.
module Minitest
       ^^^^^^^^

1 file inspected, 1 offense detected
```
