### ISSUE TITLE
Style/IndentArray probably needs consistent style too

### ISSUE THREAD

**Issue by zenspider** [bbatsov/rubocop#1609]
I can't quite tell if consistent means what I thought it means because of #1608, but I suspect it needs parallel options to IndentHash.

**Comment by jonas054** [comment]
From `config/default.yml`:

```yaml
# Checks the indentation of the first key in a hash literal.
Style/IndentHash:
  # The value `special_inside_parentheses` means that hash literals with braces
  # that have their opening brace on the same line as a surrounding opening
  # round parenthesis, shall have their first key indented relative to the
  # first position inside the parenthesis.
  # The value `consistent` means that the indentation of the first key shall
  # always be relative to the first position of the line where the opening
  # brace is.
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent
```

So `consistent` means that surrounding round parentheses of a function call don't affect the indentation rule.

```ruby
# With EnforcedStyle: special_inside_parentheses
h = {
  a: 1
}
func({
       a: 1
     },
     3)

# With EnforcedStyle: consistent
h = {
  a: 1
}
func({
  a: 1
},
     3)
```

The `consistent` style looks weird to me, which is why it's not the default, but since we have if for hashes we should probably have it for arrays too.
