### ISSUE TITLE
Not finish to search files when there is a directory named ","

### ISSUE THREAD

**Issue by naoty** [bbatsov/rubocop#1644]
I'm using 0.28.0 and ruby 2.1.5. When there is a directory named `,`, `rubocop` command will not finish. I exclude `,` directory like below to fix this. The `,` character in the pattern to search files should be escaped.

```yaml
AllCops:
  Exclude:
    - ",/**/*"
```
