### ISSUE TITLE
Indent for an expression spanning multiple lines

### ISSUE THREAD

**Issue by elyzion** [bbatsov/rubocop#1646]
Rubocop complains about the indentation on the .new and .permit_method_call lines in the code snippet below. Aligning the calls with the some_instance line resolves the complaints, but in this case it should be calculating the indent from the SomeService line. I am using version 0.29.0.

I also included my .rubocop.yml below.  Is this a Rubocop limitation, or is it something I can resolve with my configuration? (I tried the indent and align configuration options to no avail.)

```Ruby
some_instance.member.attributes =
  SomeService
    .new(@class_member)
    .permit_method_call(params[:some_key])
```
```Ruby
AlignParameters:
  EnforcedStyle: with_fixed_indentation

AsciiComments:
  Enabled: false

ClassLength:
  Max: 500

CyclomaticComplexity:
  Max: 10

LineLength:
  Max: 140

MethodLength:
  Max: 20

StringLiterals:
  EnforcedStyle: double_quotes
```

**Comment by mvz** [comment]
If I'm not mistaken, it's not the AlignParameters cop that complains here, but instead MultilineOperationIndentation.

**Comment by elyzion** [comment]
Sorry for the long break in communications. Using the following .rubocop.yml still results in the complaints about indentation.
 
```
AbcSize:
  Max: 32

AlignParameters:
  EnforcedStyle: with_fixed_indentation

AsciiComments:
  Enabled: false

ClassLength:
  Max: 500

CyclomaticComplexity:
  Max: 10

LineLength:
  Max: 140

MethodLength:
  Max: 32

MultilineOperationIndentation:
  EnforcedStyle: indented

StringLiterals:
  EnforcedStyle: double_quotes
```
I included the complaints below for reference, I hope this is just a configuration issue on our side!

```
app/services/redacted_service.rb:34:9: C: Use 2 (not 4) spaces for indenting an expression spanning multiple lines.
        .new(@class_member)
        ^^^^
app/services/redacted_service.rb:35:9: C: Use 2 (not 4) spaces for indenting an expression spanning multiple lines.
        .permit_method_call(params[:some_key])
        ^^^^^^^^^^^^^^^^^^^
```
