### ISSUE TITLE
Hidden directories should not be searched by default

### ISSUE THREAD

**Issue by sometimesfood** [bbatsov/rubocop#1656]
According to rubocop's README hidden directories should not be searched by default:

> Hidden directories (i.e., directories whose names start with a dot) are not searched by default.

However, when I upgraded to 0.29.1, rubocop started to include my `.bundle` directory by default.

Steps to reproduce:

```bash
cd $(mktemp -dt rubocop-XXXX)
cat > Gemfile <<EOS
source 'https://rubygems.org'
gem 'rubocop'
EOS
bundle install --path .bundle
bundle exec rubocop
```

For me, this results in `Inspecting 29 files`; all of them in `.bundle`. Is this the intended behaviour or should the `README` be updated?

**Comment by rrosenblum** [comment]
I have found what the issue is here. Not all of the hidden files are being linted, only the special files that have been included by the .rubocop.yml file

```
# Common configuration.
AllCops:
  # Include gemspec and Rakefile
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
  Exclude:
    - 'vendor/**/*'
```

I have a few ideas on how to fix this, but this issue raises an interesting question on what configuration should be preferred, the configuration to skip hidden files, or the configuration of files to include. I would like the input of @bbatsov and @jonas054 as to what configuration should be preferred.
