### ISSUE TITLE
Including files excluded by wildcard matching

### ISSUE THREAD

**Issue by zachahn** [bbatsov/rubocop#1670]
On my Rails project, I excluded the `config` directory (`config/**/*`) since most of the code there is not my own and updates to Rails mark differences as further conflicts.

However, I do want to lint `config/routes.rb` since we do edit that file pretty heavily.

Is there a way to do this that I overlooked? Or could we make it such that the Includes take higher priority than the Excludes?

**Comment by jonas054** [comment]
I don't see any easy solution within RuboCop because normally we want `Exclude` to override `Include`. Look at [the default configuration](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L11) where we include `Rakefile`s but exclude `vendor` directories. We don't want that to mean that `Rakefile`s in `vendor` directories shall be inspected.

So I think the best solution is if you invoke `rubocop` twice. One extra run where `config/routes.rb` is given explicitly. Then it doesn't matter that it's excluded in configuration.

**Comment by zachahn** [comment]
I see.. I hadn't noticed that before.

I can think of a "fix"... if the config is something like

```yaml
AllCops:
  # Seed is the filename patterns that are searched. I can't think of a better name right now
  Seed:
    - '*.rb'
    - '*.gemspec'
    - '*.podspec'
    - 'Gemfile'
    - 'Rakefile'
    - 'Capfile'
  Exclude:
    - 'vendor/**/*'
  Include:
    - 'vendor/lint/me.rb'
```

I can see this getting complicated, but I assume(?) that other than for including filetypes, the Include directive would generally be used as exceptions to the Exclude directives. I may or may not be able to work on a pull for this if it's deemed a good feature, but for now I'll do as you suggest. Thanks!

**Comment by perlun** [comment]
Wouldn't the "easiest" way (no idea how hard this is since I haven't looked at the code for Rubocop itself) be to let the order have precedence? I.e:

```
AllCops:
  Include:
    - 'vendor/**/*'
  Exclude:
    - 'vendor/lint/me/not.rb'
```

"Last match wins", i.e. the above use case would mean that everything except the `vendor/lint/me/not.rb` will get included.

I also see a big need for this, especially when working with older code bases (where it's not that easy to enable Rubocop for the project at large, all at once).

**Comment by zachahn** [comment]
FYI, I ended up using a regular expression (a negative lookahead) in my rubocop configuration. It's not quite optimal, but it's been working fine for me.

```yaml
AllCops:
  Exclude:
    - !ruby/regexp /\/config\/(?:(?!routes.rb).)*$/
```
