### ISSUE TITLE
Strange indentation error with if/else alignment

### ISSUE THREAD

**Issue by zmoazeni** [bbatsov/rubocop#1691]
Ruby code:

```ruby
bar = true

some_var = if bar
  "it's true!"
else
  "it's not true"
end

puts some_var
```

rubocop config:

```yaml
Style/ElseAlignment:
  Enabled: false

Lint/EndAlignment:
  Enabled: false
```

Error message:

```
foo.rb:4:3: C: Use 2 (not -9) spaces for indentation.
  "it's true!"
  ^^^^^^^^^
```

---

If I don't want to enforce if/else formats, how can I disable this without getting a warning?
