### ISSUE TITLE
Style/MethodDefParentheses doesn't support mix

### ISSUE THREAD

**Issue by zenspider** [bbatsov/rubocop#1729]
OK. I came across an actual conflict. "Seattle-Style" eschews parens on method declarations unless the args span multiple lines:

```ruby
  def self.pie_chart(diameter, pct_green,
                     good_color = PNG::Color::Green,
                     bad_color = PNG::Color::Red)
```

This is usually only when there are long names or defaults that cause the declaration to go over 80 chars.

The defaults are currently:

```yaml
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses
  SupportedStyles:
    - require_parentheses
    - require_no_parentheses
```

but could use another, called `require_no_parethesis_except_multiline` or something.
