### ISSUE TITLE
Cop requiring for space around interpolation

### ISSUE THREAD

**Issue by dziulius** [bbatsov/rubocop#1971]
There is a cop that forbids adding space around string interpolation #1836

It would be good if there was an opposite cop, which **requires** space around string interpolation:
```ruby
# Good
"some #{ interpolated } string"

# Bad
"some #{interpolated} string"
```

**Comment by jonas054** [comment]
Good addition of functionality IMO. But it should be implemented as a configuration option for `SpaceInsideStringInterpolation` rather than as a new cop:

```yaml
Style/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space
  SupportedStyles:
    - space
    - no_space
```
