### ISSUE TITLE
best way to run on files of different extension

### ISSUE THREAD

**Issue by tmornini** [bbatsov/rubocop#1983]
Hey there. As always, thanks for Rubocop and kudos to finding your way into CodeClimate's commercial product!

I'm doing some experimental work on organizing code & specs together under lib where code files are *.rb and spec files are *.spec to eliminate the "where's Waldo?" game of locating the appropriate spec in GUI editors like Sublime and also makes it much easier to notice when files don't have specs...

How can I get Rubocop to check over the .spec files? Thanks!

**Comment by jonas054** [comment]
Add `AllCops:` `Include:` `- '**/*.spec'` to your `.rubocop.yml`, and remember to add any other items you need from RuboCop's [config/default.yml](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L11-27) as your `Include` list will override (not augment) the defalt one.

Example:
```yaml
AllCops:
  Include:
    - '**/*.spec'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
```
