### ISSUE TITLE
adjusting content of rubocop messages for educational purposes

### ISSUE THREAD

**Issue by tansaku** [bbatsov/rubocop#2028]
apologies for random question, but using reek in an educational context, is there a way to configure differences to the content of the rubocop mesages?

For example, say that for education purposes we wanted to be able to modify:

```
lib/coin.rb:19:13: C: Style/RedundantSelf: Redundant self detected. (https://github.com/bbatsov/ruby-style-guide#no-self-unless-required)
  QUARTER = self.new('25')
            ^^^^^^^^^^^^^^
```

to

```
lib/coin.rb:19:13: C: Style/RedundantSelf: This line of code has a "self." prefix when it is not necessary.  This is a violation called "Redundant self" which you can read more about here: https://github.com/bbatsov/ruby-style-guide#no-self-unless-required
  QUARTER = self.new('25')
            ^^^^^^^^^^^^^^
```

would there be a simple way to do this without modifying source code?

**Comment by bbatsov** [comment]
Unfortunately, there's no such way. This was discussed in the past, but no progress was made. See https://github.com/bbatsov/rubocop/pull/799

**Comment by tansaku** [comment]
thanks @bbatsov - when you say there is no such way, you mean the current code doesn't support it rather than impossible right?

I notice that if I modify the StyleGuide parameter in enabled.yml I can adjust which URL gets associated with the report:

```
Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Enabled: true
```

So I can point to an alternate article if I want to:

```
Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'http://programmers.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width'
  Enabled: true
```

Clearly the description can be modified in the config file as well - can that also be printed out somehow?  I don't care so much about being able to change the error messages per se, just being able to add some "more details text", like so:

```
Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  Details: "You can thank the IBM punch card for this limit - it had 80 columns" 
  StyleGuide: 'http://programmers.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width'
  Enabled: true
```

Might this be easier, more practical to support?  We've got a very strong use case for this with students developers.  I read the previous discussion and it seemed to fizzle out on not having a good reason to proceed rather than a technical challenge.

We have a great reason (novices often need slightly more verbose messages than experts), and the rubocop config seems set up to all this sort of parameter configuration.

Is there more documentation on what other parameters can be used in the cops?  I've read https://github.com/bbatsov/rubocop#generic-configuration-parameters but it doesn't mention the StyleGuide or Description parameters and I can't find any other reference to those two in the README.

I'm trying to get something similar working with the reek project https://github.com/troessner/reek/issues/589 where we are considering using internationalization features to support custom messages, but I'm guessing there's actually less work to support similar in rubocop, since it's already set up to make the contents of the config available to the cop ...
