### ISSUE TITLE
Configuration & File Path

### ISSUE THREAD

**Issue by jamescmartinez** [bbatsov/rubocop#2132]
My configuration file is not excluding the correct files since my upgrade from 0.29.1 to 0.33.0 unless I make a change to the path. Here's the diff that makes it work again (paths generated by `.rubocop_todo.yml`)

Old:
```
-    - 'bin/**/*'
-    - 'db/**/*'
```
New:
```
+    - '../../Development/my-project/bin/**/*'
+    - '../../Development/my-project/db/**/*'
```

How can I bring these back to the first two lines?

**Comment by mattjmcnaughton** [comment]
I might be totally off with this, but it looks like in your old code you have 
``bin/**/*`` instead of `'bin/**/*'` (backticks instead of quotes). And then the new code uses quotes for both - could that be the source of the issue?

**Comment by jamescmartinez** [comment]
@mattjmcnaughton That was a great sight, but unfortunately, that's not it. I edited the original post to reflect quotes instead of backticks.

**Comment by jonas054** [comment]
Are you running `rubocop` from a directory other than the project root? Or where do the relative paths come from?

**Comment by jamescmartinez** [comment]
@jonas054 I'm running it from project root. To be honest, I'm not sure where the relative paths are coming from.

**Comment by mattjmcnaughton** [comment]
Ah gotcha!

Do you mind posting the rest of the `.rubocop.yml` and the rest of `.rubocop_todo.yml`? I think that info might be helpful.

**Comment by jamescmartinez** [comment]
Sure!

```yaml
AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
```
