### ISSUE TITLE
When running RuboCop is run as a rake task it fails, but not if not a rake task

### ISSUE THREAD

**Issue by ericbrooke** [bbatsov/rubocop#2134]
Response when running just rubocop
```
rubocop
Inspecting 400 files
................................................................................................................................................................................................................................................................................................................................................................................................................

400 files inspected, no offenses detected
```
When running rubocop via rake task
```
rake
Running RuboCop...
Inspecting 400 files
......................................................................................................................................................
To see the complete backtrace run rubocop -d.
..........................................................................................................................................................................................................................................................

400 files inspected, no offenses detected


Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.33.0 (using Parser 2.2.2.6, running on ruby 2.2.2 x86_64-darwin14)
RuboCop failed!
```

Rakefile
```
require File.expand_path('../config/application', __FILE__)
Rails.application.load_tasks

if %w(development test).include? Rails.env
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new

  task(:default).clear
  task default: [:rubocop, :spec]
end
```

.rubocop.yml
```
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Guardfile'
  DisplayCopNames: true
  RunRailsCops: true

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 99
  Exclude:
    - 'config/**/*'

Metrics/ModuleLength:
  Max: 150

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Validation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/controllers/*'

Style/RegexpLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false
```

rubocop -D also works with no problem
