### ISSUE TITLE
--auto-gen-config not resolving all offenses after upgrading from 0.32.1

### ISSUE THREAD

**Issue by maxjacobson** [bbatsov/rubocop#2228]
I'm having trouble reproducing this in an isolated code base, so here's the relevant information:

* 1779 ruby files
* many offenses listed in the `.rubocop_todo.yml` file, which was generated by rubocop 0.32.1
* everything is green in rubocop 0.32.1, but I'm trying to upgrade
* the `Lint/EndAlignment` cop is set to `AlignWith: variable`
* I have no `Lint/EndAlignment` offenses, but `Style/ElseAlignment` is disabled in the todo file
* I upgrade to a newer rubocop (both 0.33 and 0.34 have this behavior), and now I have some new offenses, because some new cops were introduced
* (my `.rubocop_todo.yml` is still the one generated by 0.32.1)
* I don't want to resolve all of the new offenses right now, I'd rather just regenerate the `.rubocop_todo.yml` file, so I run `bin/rubocop --auto-gen-config` and it regenerates my `.rubocop_todo.yml` file.

At this point, when I run `bin/rubocop`, there should be no offenses, right?

I start getting a bunch of `Style/ElseAlignment` offenses.

Before the regeneration (excerpts):

```yaml
# .rubocop_todo.yml
Style/ElseAlignment:
  Enabled: false

# .rubocop.yml
inherit_from .rubocop_todo.yml
Lint/EndAlignment:
  AlignWith: variable
```

After the regeneration (excerpts):

```yaml
# .rubocop_todo.yml
Lint/EndAlignment:
  Enabled: false

# .rubocop.yml
inherit_from .rubocop_todo.yml
Lint/EndAlignment:
  AlignWith: variable
```

Two interesting things:

1. `Lint/EndAlignment` is disabled even though it's got a configuration (new offenses seem to have been discovered in 0.33 related to the alignment of the `end` of case statements, but I'm not sure which entry in the changelog is responsible for this)
2. `Style/ElseAlignment` is no longer disabled, even though those offenses didn't go anywhere, so now I have a bunch of new offenses

Desired behavior: after running `bin/rubocop --auto-gen-config`, there would be no offenses
