### ISSUE TITLE
Settings global exclude pattern in my $HOME/.rubocop.yml

### ISSUE THREAD

**Issue by zw963** [bbatsov/rubocop#2261]
I want to add all my project exclude pattern in my $HOME/.rubycop.yml

so, I have to add like this:
```yml
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
  - '**/vendor/**/*'
  - '**/spec/fixtures/**/*'
  - '**/db/schema.rb'
  - '**/db/migrate/*'
  - '**/bin/bundle'
  - '**/bin/rails'
  - '**/bin/rake'
  - '**/bin/setup'
  - '**/bin/spring'
  - '**/config/**/*'
  - '**/script/**/*'
```

But, I think it maybe not reasonable, if remove the leading ``** `` is more reasonable.
no one hope exclude some directory in $HOME after all.

Thanks
