### ISSUE TITLE
Enable or disable groups of cops?

### ISSUE THREAD

**Issue by marnen** [bbatsov/rubocop#2343]
Is it possible to set configuration options by group? I'd love to be able to do

```yaml
Style:
  Enabled: false
Metrics:
  Enabled: true
```

Maybe even overrides:

```yaml
Style:
  Enabled: false
Metrics:
  Enabled: true
Metrics/UselessMetric:
  Enabled: false
```
...though that may be less necessary.

Basically, what I'm looking for is a generalized version of `RunRailsCops`. Does this exist?
