### ISSUE TITLE
Rubocop does not disable style/andor

### ISSUE THREAD

**Issue by bytenel** [bbatsov/rubocop#2373]
I have rubocop enabled and it lints my project. In my project I have one file with a line like the following. Rubocop keeps saying there is an error on the line. My config is included.

```
 def redirect_to_squarespace
    post = Post.find_by_slug(params[:id])
    url = build_squarespace_post_url(post)
    # and / or are appropriate to use for control flow, not for conditionals
    # rubocop: disable Style/AndOr
    redirect_to url and return
    # rubocop:enable
  end
```

Config
```
require: rubocop-rspec
AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'db/**/*.rb'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
Style/CaseIndentation:
  IndentWhenRelativeTo: case
  IndentOneStep: true
Style/FirstParameterIndentation:
  EnforcedStyle: consistent
Style/SpaceInsideStringInterpolation:
  Enabled: false
```

The error I get is
```
app/controllers/blogs_controller.rb:35:21: C: Style/AndOr: Use && instead of and. (https://github.com/bbatsov/ruby-style-guide#no-and-or-or)
    redirect_to url and return
                    ^^^
```

Edit:

The weird thing is I have the following method listed afterwards and it seems to work properly
```
  def redirect_to_squarespace_admin
    # and / or are appropriate to use for control flow, not for conditionals
    # rubocop: disable Style/AndOr
    redirect_to "#{ squarespace_url }/config" and return
    # rubocop: enable
  end
end
```
