### ISSUE TITLE
DisabledByDefault doesn't appear to merge properly

### ISSUE THREAD

**Issue by thommay** [bbatsov/rubocop#2467]
given a config file:

```yaml
inherit_gem:
  rubocop: config/default.yml

AllCops:
  DisabledByDefault: true
```

I'd expect all cops to be disabled, however the default set of cops is applied:
```
11:00 ~/code/rubocop % be bin/rubocop -c /Users/thom/work/chefstyle/config/chefstyle.yml /Users/thom/work/chefstyle -f simple
[...]
6 files inspected, 51 offenses detected
```

Removing the `inherit_gem` section correctly results in no cops being applied:
```
1:01 ~/code/rubocop % be bin/rubocop -c /Users/thom/work/chefstyle/config/chefstyle.yml /Users/thom/work/chefstyle -f simple
6 files inspected, no offenses detected
```
