### ISSUE TITLE
Exclude not working for AllCops in .rubocop.yml?

### ISSUE THREAD

**Issue by RST-J** [bbatsov/rubocop#2492]
I have some code that I don't want to be checked by the cops and hence configured the respective files to be excluded in `.rubocop.yml`:
```YAML
AllCops:
  Exclude:
    - 'app/controllers/commontator/*.rb'
```
Unfortunately, the cops are run for files within that directory. If I explicitly exclude the same pattern for one of the violated cops, the violation is not reported anymore:
```YAML
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/commontator/*.rb'
```
Any idea why that is the case? I'm using rubocop 0.35.1 and this is the complete config (without the pattern in question):
```YAML
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
  DisplayCopNames: true
  RunRailsCops: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 20

```

**Comment by jonas054** [comment]
So if you add the exclusion in question, so that your `.rubocop.yml` becomes
```yaml
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'app/controllers/commontator/*.rb'
  DisplayCopNames: true
  RunRailsCops: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 20
```
and run `rubocop --list`, then files under `app/controllers/commontator/` show up in the list?
