### ISSUE TITLE
auto-gen-config generated Style/GuardClause Exclude doesn't seem to work

### ISSUE THREAD

**Issue by cthiel** [bbatsov/rubocop#2679]
Running `rubocop --auto-gen-config` generated a config like:

```
Style/GuardClause:
  Exclude:
    - 'app/controllers/some_controller.rb'
```

but running rubocop again with that config would still report the same error in some_controller.rb

Only setting

```
Style/GuardClause:
  Enabled: false
```

turned it off effectively. Exclude lists seem to work correctly for other Style/\* cops.

**Comment by jonas054** [comment]
Do you have an `Exclude` property for `Style/GuardClause` set somewhere else, for example in `.rubocop.yml`?

**Comment by cthiel** [comment]
No.

**Comment by jonas054** [comment]
I've been trying to reproduce the problem, but have not been able to. @cthiel Can you create a minimal set-up that causes the problem?

**Comment by TimMoore** [comment]
I also have a problem like this. When I run `rubocop --auto-gen-config`, it generates a `.rubocop_todo.yml` with 7 offenders excluded:

```yml
# Offense count: 7
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/exit_responses_controller.rb'
    - 'app/controllers/participant_controller.rb'
    - 'app/helpers/excel_helper.rb'
    - 'app/helpers/response_helper.rb'
    - 'lib/comments/comment_query.rb'
    - 'vendor/appamp/lib/controlamp/component.rb'
```

Then, if I immediately run `rubocop` again, it finds many more violations. It isn't immediately obvious what's different between the cases it picks up in `--auto-gen-config` and those it does not.
