### ISSUE TITLE
--auto-gen-config sets a value to "-Infinity" for WordArray

### ISSUE THREAD

**Issue by maxjacobson** [bbatsov/rubocop#2740]
I haven't investigated exactly why this is occurring yet, but running `rubocop --auto-gen-config` with Rubocop 0.36 on a codebase generated this config:

``` yaml
Style/WordArray:
  EnforcedStyle: percent
  MinSize: -Infinity
```

And this config is invalid and leads to errors later when it's loaded. I don't think our word arrays are particularly unusual -- we have 4 of them, ranging in length from 2 to 3 elements.

**Comment by jonas054** [comment]
I think we need more help with reproducing. Do you use square brackets or `%w` in the word arrays you have? What's your configured style before running `rubocop --auto-gen-config`?

**Comment by maxjacobson** [comment]
Using square brackets before

The earlier style (from an earlier run of `rubocop --auto-gen-config`) was:

```yaml
# Offense count: 2                                                                  
# Cop supports --auto-correct.                                                      
# Configuration parameters: WordRegex.                                              
Style/WordArray:                                                                    
  MinSize: 3                                                                        
```
