### ISSUE TITLE
`TrailingComma*` styles don't correctly identify multiline literals

### ISSUE THREAD

**Issue by fj** [bbatsov/rubocop#2742]
```
# version
 ψ rubocop -V
0.36.0 (using Parser 2.3.0.2, running on ruby 2.3.0 x86_64-linux)
```

```yaml
# .rubocop.yml
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
```

```ruby
# foo.rb
    let(:available_channels) { [{name: channel_name, api_identifier: channel_api_id}] }
```

Rubocop complains:

```
foo.rb:1:33: C: Style/TrailingCommaInLiteral: Put a comma after the last item of a multiline array.                                    
    let(:available_channels) { [{name: channel_name, api_identifier: channel_api_id}] }
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

but this is not a multiline array; in fact, there's only one line in the whole file so it can't be a multiline array by definition!
