### ISSUE TITLE
Style/IndentationWidth reports weird indentation 

### ISSUE THREAD

**Issue by NekoNova** [bbatsov/rubocop#2765]
Hello,

I have the following snippet of code:

```
def cookies
    cookie_ids = if self.home_made? 
      Cookie.home_made_cookie_ids
    elsif self.store_bought?
      Cookie.store_bought_ids
    elsif self.grandma?
      Cookie.grandma_ids
    else
      raise NotImplementedError
    end

    Cookie::Base.where(id: cookie_ids)
  end
```

Which is how we currently code our assignments.
We have the following cops defined for alignment:

```
inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.3

Lint/EndAlignment:
  AlignWith: variable
```

this is reported in the console:
```
app/models/cookie.rb:8:7: C: Style/IndentationWidth: Use 2 (not -14) spaces for indentation.
      Cookie.home_made_cookie_ids
      ^^^^^^^^^^^^^^
```

I don't understand why this one is being triggered.
When I change the first line to indent 6 tabs, the Cop actually accepts the file, ignoring all other lines.
