### ISSUE TITLE
Migration between deprecated cop rules sucks

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#2783]
How should I deal with having 100s of engineers needing to upgrade in unison? (Most are using editor integration so just using `bundle exec rubocop` won't work).

Right now I have this in my config:

```
Style/TrailingComma:
  EnforcedStyleForMultiline: consistent_comma
```

And I need to have

```
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
```

If I put the new options in now, they spew but the old version works. Great. But when someone uses the new version it stops and emits:

```
Error: The `Style/TrailingComma` cop no longer exists. Please use `Style/TrailingCommaInLiteral` and/or `Style/TrailingCommaInArguments` instead.
(obsolete configuration found in .rubocop.yml, please update it)
```

If I leave the old config only then the new version pukes with the same. How the heck do I migrate this for everyone at my company?
