### ISSUE TITLE
Problem with Style/StringLiterals:  

### ISSUE THREAD

**Issue by NekoNova** [bbatsov/rubocop#2834]
Hello,

I'm running into problems with Rubocop when activating this rule.
This is the autoput when running the command with -d:

```
rubocop -d app/business_objects/data_hub/adapters/bureau_van_dijk/query_string_builder.rb 

For /Users/olivar/RubymineProjects/riskmethods: configuration from /Users/olivar/RubymineProjects/riskmethods/.rubocop.yml
Inheriting configuration from /Users/olivar/RubymineProjects/riskmethods/.rubocop_todo.yml
Default configuration from /Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/config/default.yml
Inheriting configuration from /Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/config/enabled.yml
Inheriting configuration from /Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/config/disabled.yml
Inspecting 1 file
Scanning /Users/olivar/RubymineProjects/riskmethods/app/business_objects/data_hub/adapters/bureau_van_dijk/query_string_builder.rb
An error occurred while Style/StringLiterals cop was inspecting /Users/olivar/RubymineProjects/riskmethods/app/business_objects/data_hub/adapters/bureau_van_dijk/query_string_builder.rb.
undefined method `source' for nil:NilClass
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/style/string_literals.rb:24:in `block in on_dstr'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/style/string_literals.rb:24:in `map'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/style/string_literals.rb:24:in `on_dstr'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:39:in `block (2 levels) in on_dstr'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:97:in `with_cop_error_handling'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:38:in `block in on_dstr'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:37:in `each'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:37:in `on_dstr'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:123:in `on_defs'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_defs'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_begin'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:89:in `on_class'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_class'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_module'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_module'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_module'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:13:in `walk'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:56:in `investigate'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/team.rb:58:in `inspect_file'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:194:in `inspect_file'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:164:in `block in do_inspection_loop'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:158:in `loop'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:158:in `do_inspection_loop'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:87:in `process_file'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:57:in `each'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:35:in `run'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cli.rb:30:in `run'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/bin/rubocop:14:in `block in <top (required)>'
/Users/olivar/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/bin/rubocop:13:in `<top (required)>'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/bin/rubocop:23:in `load'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/bin/rubocop:23:in `<main>'
An error occurred while Style/StringLiterals cop was inspecting /Users/olivar/RubymineProjects/riskmethods/app/business_objects/data_hub/adapters/bureau_van_dijk/query_string_builder.rb.
undefined method `source' for nil:NilClass
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/style/string_literals.rb:24:in `block in on_dstr'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/style/string_literals.rb:24:in `map'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/style/string_literals.rb:24:in `on_dstr'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:39:in `block (2 levels) in on_dstr'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:97:in `with_cop_error_handling'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:38:in `block in on_dstr'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:37:in `each'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:37:in `on_dstr'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:123:in `on_defs'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_defs'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_begin'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:89:in `on_class'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_class'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_module'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_module'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:43:in `on_module'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/ast_node/traversal.rb:13:in `walk'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/commissioner.rb:56:in `investigate'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cop/team.rb:58:in `inspect_file'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:194:in `inspect_file'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:164:in `block in do_inspection_loop'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:158:in `loop'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:158:in `do_inspection_loop'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:87:in `process_file'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:57:in `each'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/runner.rb:35:in `run'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/lib/rubocop/cli.rb:30:in `run'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/bin/rubocop:14:in `block in <top (required)>'
/Users/olivar/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/gems/rubocop-0.37.0/bin/rubocop:13:in `<top (required)>'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/bin/rubocop:23:in `load'
/Users/olivar/.rvm/gems/ruby-2.2.3@riskmethods/bin/rubocop:23:in `<main>'
.

1 file inspected, no offenses detected

2 errors occurred:
An error occurred while Style/StringLiterals cop was inspecting /Users/olivar/RubymineProjects/riskmethods/app/business_objects/data_hub/adapters/bureau_van_dijk/query_string_builder.rb.
An error occurred while Style/StringLiterals cop was inspecting /Users/olivar/RubymineProjects/riskmethods/app/business_objects/data_hub/adapters/bureau_van_dijk/query_string_builder.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.37.0 (using Parser 2.3.0.3, running on ruby 2.2.3 x86_64-darwin14)
Finished in 0.3767494599997008 seconds
```

I cannot share the source, but the class is basically one class with 2 class methods that return very large strings to use in queries.
The strings are build up using:

```
def method
  <<-QUERY_STRING







  QUERY_STRING
end
```
and are roughly 20 lines long.

**Comment by NekoNova** [comment]
update : this happens with a lot of other files in our project. All seem to be related to multi line strings;
This is our config:

```
inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.3

# This rule checks whether the *end* keyword is always properly aligned with the variable
# it belongs to.
Lint/EndAlignment:
  AlignWith: variable

# This rule checks whether the alignment of hashes is following the correct configuration:
# All entries are aligned on keys, and no exceptions are allowed.
Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

# This rule checks whether all string literals in the source code follow the agreed rule.
# For Riskmethods, this is single quotes.
Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

# This rule checks whether string literals used inside interpolated strings are following the
# configured rule, which for Riskmethods is single quotes.
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

# This rule checks whether procs are properly written as symbol procs, unless the method in question
# is inside the ignore whitelist.
Style/SymbolProc:
  IgnoredMethods:
    - respond_to

# This rule checks whether trailing comma's are removed from string literals.
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma

# This rule enforces the removal of trivial accessors in the code, keeping the code base clean.
Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: false
  AllowDSLWriters: false
  IgnoreClassMethods: false
  Whitelist:
    - to_ary
    - to_a
    - to_c
    - to_enum
    - to_h
    - to_hash
    - to_i
    - to_int
    - to_io
    - to_open
    - to_path
    - to_proc
    - to_r
    - to_regexp
    - to_str
    - to_s
    - to_sym
```
