### ISSUE TITLE
Multiline autofixers have incorrect indentation for method call

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#2843]
Turning on all the multiline Cops like:

```
Style/FirstArrayElementLineBreak:
  Enabled: true
Style/FirstHashElementLineBreak:
  Enabled: true
Style/FirstMethodArgumentLineBreak:
  Enabled: true
Style/FirstMethodParameterLineBreak:
  Enabled: true
Style/MultilineArrayBraceLayout:
  Enabled: true
Style/MultilineHashBraceLayout:
  Enabled: true
Style/MultilineMethodCallBraceLayout:
  Enabled: true
Style/MultilineMethodDefinitionBraceLayout:
  Enabled: true
```

The autofixer will change

```
def foo
  bar(a,
    b,
  )
end
```

to

```
def foo
  bar(
    a,
    b,
)
```

but it should be

```
def foo
  bar(
    a,
    b,
  )
```

Is there a cop that I'm missing to put the `)` at the correct width?

/cc @jonas054 @panthomakos since you seem to have worked on these.
