### ISSUE TITLE
Style/IndentationWidth should have a consistent style

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#2849]
We'd like to have something like these:

```
Style/IndentHash:
  EnforcedStyle: consistent
Style/IndentArray:
  EnforcedStyle: consistent
Style/FirstParameterIndentation:
  EnforcedStyle: consistent
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
```

but would change this code:

```
foo(
  bar, baz do
         1
       end
)
```

into this

```
foo(
  bar, baz do
    1
  end
)
```
