### ISSUE TITLE
Command line rubocop passes, precommit hook throws Style/FileName in Gemfile

### ISSUE THREAD

**Issue by pmichna** [bbatsov/rubocop#2973]
When I run `rubocop` in my project everything passes.

I have turned on the precommit hook with overcommit. When trying to commit I get:

```
Errors on lines you didn't modify:
/Users/Pawel/code/project/Gemfile:1:1: C: Style/FileName: Use snake_case for source file names.
```

Why are these two results different?

The output of `rubocop -V`:

```
$ rubocop -V
0.38.0 (using Parser 2.3.0.6, running on ruby 2.2.3 x86_64-darwin14)

$ overcommit -v
overcommit 0.32.0
```

The first line of Gemfile that is allegedly wrong:

```
source 'https://rubygems.org'
```

.rubocop.yml:

```
inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
```

.overcommit.yml:

```
PreCommit:
  RuboCop:
    enabled: true
```
