### ISSUE TITLE
Style/WordArray autofix ignores Style/PercentLiteralDelimiters settings.

### ISSUE THREAD

**Issue by rwz** [bbatsov/rubocop#3031]
I have the following configuration:

```yaml
Style/PercentLiteralDelimiters:
  Description: "Use `%`-literal delimiters consistently"
  Enabled: true
  PreferredDelimiters:
    "%i": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"
    "%x": "[]"

Style/WordArray:
  Description: "Use %w or %W for arrays of words."
  Enabled: true
```

When I run `rubocop --only Style/WordArray -a` it fixes all occurences of word-arrays to use `%w()` syntax.

I was expecting it to use the settings of the `PercentLiteralDelimiters` cop and fix word-arrays to use the `%w[]` syntax.

My version of rubocop is 0.39.0, which is the latest at this point.
