### ISSUE TITLE
Warning: unrecognized parameter Style/AlignParameters:IndentationWidth

### ISSUE THREAD

**Issue by donv** [bbatsov/rubocop#3095]
## Expected behavior

No warning.

## Actual behavior

    Warning: unrecognized parameter Style/AlignParameters:IndentationWidth found in /path/to/my/.rubocop.yml

**However, the cop works as expected.**

## Steps to reproduce the problem

Add config:

```yaml
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4
```

Run rubocop

## RuboCop version

```
$ rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.3.0 x86_64-darwin14)
```

**Comment by mikegee** [comment]
Yup, `IndentationWidth` isn't a parameter:

```
% bin/rubocop --show-cop Style/AlignParameters
# Supports --auto-correct
Style/AlignParameters:
  Description: Align the parameters of a method call if they span more than one line.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-double-indent
  Enabled: true
  EnforcedStyle: with_first_parameter
  SupportedStyles:
  - with_first_parameter
  - with_fixed_indentation
```

I'm not sure why you would expect no warning when providing an unrecognized parameter.
