### ISSUE TITLE
Syntax error caused by autocorrecting Style/MultilineMethodCallBraceLayout

### ISSUE THREAD

**Issue by tpbowden** [bbatsov/rubocop#3121]
Using 0.40.0 (using Parser 2.3.1.0, running on ruby 2.3.1 x86_64-darwin15)

Given the following code:

```ruby
OpenStruct.new(first_arg: 'foo',
               second_arg: 'bar',
               third_arg: 'baz',
              ) 
```

running `rubocop -a` will produce the following:

```ruby
OpenStruct.new(first_arg: 'foo',
               second_arg: 'bar',
               third_arg: 'baz'),
```

The trailing comma after the closing paren is actually a syntax error and should have been removed.

This behaviour is also present in Style/MultilineArrayBraceLayout

**Comment by ptarjan** [comment]
👍

**Comment by alexdowad** [comment]
Can't repro. Please post whatever part of your `.rubocop.yml` is necessary to make the problem reproducible.

**Comment by tpbowden** [comment]
Ah yes you're right, here is the config I've used to reproduce. It looks like the problem is caused by combining with `Style/TrailingCommaInArguments: comma`:

```yaml
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/MultilineMethodCallBraceLayout:
  Enabled: true
Style/MultilineArrayBraceLayout:
  Enabled: true
```
