### ISSUE TITLE
Whitelisting / incremental workflow

### ISSUE THREAD

**Issue by grosser** [bbatsov/rubocop#3143]
I want to add rubocop to a giant app one folder at a time, but doing

```
AllCops:
  Include:
    - 'Rakefile'
    - 'config.ru'
    - 'lib/foo/*'
  Exclude:
    - '**/*'
```

but that produces 0 files ... is there a way to do that ?

**Comment by palkan** [comment]
It happens due to "**/*"  exclude path. Rubocop first _includes_ all paths matching `Include` and then filters out all files matching `Exclude`.
So, just remove your `Exclude`.

**Comment by grosser** [comment]
```
AllCops:
  TargetRubyVersion: 2.1
  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
```

-> Inspecting 5278 files :D
