### ISSUE TITLE
Teach Style/BlockDelimiters that blocks can be used as params

### ISSUE THREAD

**Issue by thegranddesign** [bbatsov/rubocop#3187]
Given the following config:

```yaml
Style/BlockDelimiters:
  Enabled:                       true
  EnforcedStyle:                 'braces_for_chaining'
```

And given a lambda being passed as an argument to a method such as:

```ruby
has_many :foos, lambda { |model|
  # do stuff with model
}, class_name: 'Bar'
```

`BlockDelimiters will attempt to convert it to:

```ruby
has_many :foos, lambda do |model|
  # do stuff with model
end, class_name: 'Bar'
```

Which is not valid Ruby and will not parse.

## RuboCop version

Include the output of `rubocop -V`:

```
$ rubocop -V
0.40.0 (using Parser 2.3.1.0, running on ruby 2.3.0 x86_64-darwin15)
```
