### ISSUE TITLE
RuboCop does't recognize Ruby 2.3.1 in .ruby-version

### ISSUE THREAD

**Issue by Quintasan** [bbatsov/rubocop#3267]
## Expected behavior

Rubocop executes normally

## Actual behavior

Executing `rubocop` fails with:

```
Error: Unknown Ruby version 0.0 found in `.ruby-version`.
Known versions: 1.9, 2.0, 2.1, 2.2, 2.3
```

## Steps to reproduce the problem

1. `rails new appname`
2. Install Rubocop
3. `rvm use --create --ruby-version 2.3.1@appname`
4. `cd appname`
5. `rubocop`

## RuboCop version

Include the output of `rubocop -V`:

```
$ rubocop -V
0.41.1 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-linux)
```

## Additional information

.ruby_version:
```
ruby-2.3.1
```

.rubocop.yml:
```
Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
(...)
```
