### ISSUE TITLE
Can't disable the "Extra empty line detected at block body beginning" message

### ISSUE THREAD

**Issue by marko-avlijas** [bbatsov/rubocop#3332]
I am using http://relaxed.ruby.style/rubocop.yml

I can't seem to disable the `Extra empty line detected at block body beginning` message. Notice the **block** part.

I have successfuly disabled Style/EmptyLines and Style/EmptyLinesAroundBody, but this rule looks like ain't documented.

These are my modifications of rubocop.yml
```
Style/EmptyLines:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#nosuchlink

Style/EmptyLinesAroundBody:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#nosuchlink
```

How to find that rule and how to disable it?
