### ISSUE TITLE
Default configuration of `Style/Alias` doesn't match the style guide recommendation

### ISSUE THREAD

**Issue by Drenmi** [bbatsov/rubocop#3619]
Our default configuration has the following:

```yaml
# config/default.yml
Style/Alias:
  EnforcedStyle: prefer_alias
```

but the [style guide](https://github.com/bbatsov/ruby-style-guide#alias-method) recommends:

> Always use alias_method when aliasing methods of modules, classes, or singleton classes at runtime, as the lexical scope of alias leads to unpredictability in these cases.

Not sure how many people we might surprise by changing it now, though. 😅
