### ISSUE TITLE
Make Style/EndOfLine configurable

### ISSUE THREAD

**Issue by jonas054** [bbatsov/rubocop#3800]
Based on discussions in #3401, I propose to add the following configuration option:

```yaml
Style/EndOfLine:
  EnforcedStyle: lf
  SupportedStyles:
    - lf
    - crlf
    - native
```

The `native` option means `crlf` on Windows and `lf` on other platforms, and is the best choice for people running on Windows with `core.autocrlf = true`, if they are using git.
