### ISSUE TITLE
Lint/UnneededDisable of Metrics/LineLength that isn't unneeded

### ISSUE THREAD

**Issue by jfelchner** [bbatsov/rubocop#4001]
This line (among many others) is throwing an error for me:

```ruby
  LARGE_DATA_STRING_PATTERN = %r{\A([A-Za-z0-9\+\/#]*\={0,2})#([A-Za-z0-9\+\/#]*\={0,2})#([A-Za-z0-9\+\/#]*\={0,2})\z} # rubocop:disable Metrics/LineLength
```

My full `LineLength` config is as follows:

```yaml
Metrics/LineLength:
  Enabled:                       true
  Max:                           90
  AllowHeredoc:                  true
  AllowURI:                      true
  IgnoreCopDirectives:           true
  URISchemes:
    - 'http'
    - 'https'
```

--------

## Expected behavior

No error for `Lint/UnneededDisable`

## Actual behavior

An error for `Lint/UnneededDisable`

## RuboCop version

```
$ rubocop -V
0.47.1 (using Parser 2.3.3.1, running on ruby 2.4.0 x86_64-darwin16)
```
