### ISSUE TITLE
Style/MultilineArrayBraceLayout auto-correct with comments breaks code

### ISSUE THREAD

**Issue by dinatih** [bbatsov/rubocop#4101]
## Expected behavior
with : 
```ruby
# test.rb
def my_method?
  [true, # my comment #1
   true # my_comment #2
  ].any?
end
```
after `$ rubocop -a test.rb ` we should expect : 
```ruby
# test.rb
def my_method?
  [true, # my comment #1
   true].any? # my_comment #2  
end
```
or nothing : 
```ruby
# test.rb
def my_method?
  [true, # my comment #1
   true # my_comment #2  
  ].any?
end
```
## Actual behavior

but got : 
```ruby
def my_method?
  [true, # my comment #1
   true] # my_comment #2.any?
end
```

the `any?` chained call is move behind the \# and got commented
## Steps to reproduce the problem
see **Expected behavior**

here my rubocop.yml without `Style/MultilineArrayBraceLayout` override if needed: 
```yml
AllCops:
  Exclude:
   - 'bin/*'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3
Metrics/LineLength:
  Max: 126 # Github fixed web line length
Metrics/CyclomaticComplexity:
  Max: 6
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/AlignHash:
  EnforcedColonStyle: table
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false # Default in ruby 3, so don't need to worry about, except we go some memory leaks
Style/IfUnlessModifier:
  MaxLineLength: 126
Style/IndentationConsistency:
  EnforcedStyle: rails
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/WhileUntilModifier:
  MaxLineLength: 126
```
## RuboCop version
```
$ rubocop -V
0.47.1
```
