### ISSUE TITLE
Cop suggestion: always use of the new hash syntax (with comma) where possible

### ISSUE THREAD

**Issue by mickaeltr** [bbatsov/rubocop#4167]
## Expected behavior

I would like Rubocop to fail / autocorrect when I am using arrows for building hash objects, since [a new hash syntax was introduced with Ruby 1.9](http://breakthebit.org/post/8453341914/ruby-19-and-the-new-hash-syntax).

## Actual behavior

Both styles (with arrows and commas) are allowed.

## Steps to reproduce the problem

`{'foo => 'bar'}` should be auto-corrected in `{foo: 'bar'}`

## RuboCop version

0.47.1

**Comment by Drenmi** [comment]
You mean [`Style/HashSyntax`](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L333)? 🙂

**Comment by mickaeltr** [comment]
Oh yes, thanks, I was surprised not to find that in the existing cops.
Yet I have to figure out why it doesn't apply on my project.

**Comment by mickaeltr** [comment]
Before I close that issue, any idea why I don't see this cop applying on my project?

This is my `.rubocop.yml` file (on ruby-2.3.1):
```
Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 400

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Max: 400

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/AccessorMethodName:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false
```
