### ISSUE TITLE
Style/SymbolArray autocorrects without respecting Style/PercentLiteralDelimiters

### ISSUE THREAD

**Issue by brandonweiss** [bbatsov/rubocop#4199]
```yaml
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "[]"
```

Will autocorrect `[:foo, :bar]` to `%i(foo bar)`.
