### ISSUE TITLE
PercentLiteralDelimiters/PreferredDelimiters ignores default value

### ISSUE THREAD

**Issue by xeron** [bbatsov/rubocop#4263]
Rubocop ignores following configuration:

```yaml
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
```

```
$ rubocop -D
Inspecting 60 files
.......C.................CC....................C...........C

Offenses:

app/controllers/users_controller.rb:2:46: C: Style/PercentLiteralDelimiters: %i-literals should be delimited by [ and ].
  before_action :authenticate_user!, except: %i(create failure logout)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
config/deploy/production.rb:1:61: C: Style/PercentLiteralDelimiters: %w-literals should be delimited by [ and ].
server 'gcal-sms.xeron.me:22001', user: 'webmaster', roles: %w(app db web resque_worker resque_scheduler)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/deploy/staging.rb:1:61: C: Style/PercentLiteralDelimiters: %w-literals should be delimited by [ and ].
server 'gcal-sms.xeron.me:22001', user: 'webmaster', roles: %w(app db web resque_worker resque_scheduler)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
config/spring.rb:1:1: C: Style/PercentLiteralDelimiters: %w-literals should be delimited by [ and ].
%w( ...
^^^
test/test_helper.rb:5:14: C: Style/PercentLiteralDelimiters: %w-literals should be delimited by [ and ].
  add_filter %w( ...
             ^^^

60 files inspected, 5 offenses detected
```

It only works if I add specific literals:

```yaml
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()
```

```
$ rubocop -D
Inspecting 60 files
............................................................

60 files inspected, no offenses detected
```

--------

## Expected behavior

Do not show any offenses.

## Actual behavior

Rubocop suggests to replace `()` delimiters with `[]` even if default is set to `()`.

## Steps to reproduce the problem

.rubocop.yml:
```yaml
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
```

test.rb:
```ruby
puts %w(a b c)
```

```
$ rubocop -D
Inspecting 1 file
C

Offenses:

test.rb:1:6: C: Style/PercentLiteralDelimiters: %w-literals should be delimited by [ and ].
puts %w(a b c)
     ^^^^^^^^^

1 file inspected, 1 offense detected
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.3.3 x86_64-darwin15)
```
