### ISSUE TITLE
Style/ConditionalAssignment does not report when Metrics/LineLength set to less than 86

### ISSUE THREAD

**Issue by bunufi** [bbatsov/rubocop#4418]
`Style/ConditionalAssignment` does not report an offense if `Metrics/LineLength` is set to less than 96.

--------

## Expected behavior

Changing settings to `Metrics/LineLength` should not affect outcome of other cops. 

## Actual behavior

Offense is not reported when it should be. 

## Steps to reproduce the problem

Have some code that offends Style/ConditionalAssignment cop. Such as: 
```
def do_this_do_that(field, value, filter)
  if filter
    @i_do_not_believe_in_unicorns << { field => value }
  else
    @i_do_not_believe_in_unicorns << { field => 'i drink bear' }
  end
end
```

Set following rubocop settings: 
```
Metrics/LineLength:
  Max: 95

Style/ConditionalAssignment:
  Enabled: true
```
Outcome: 
No offenses

Change settings to (line length more than 95): 
```
Metrics/LineLength:
  Max: 96

Style/ConditionalAssignment:
  Enabled: true
```
Outcome: 
`Style/ConditionalAssignment` reports an offense

Note:
Specified cops are the only cops that are defined. The rest are defaults
I have noticed that line length changes depending on the code. Initially line lengths were 85 and 86, but after changing to my preferred method names it increased to 95, 96. 

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.46.0
0.48.1
0.49.0

same behavior with all version listed above.
```
