### ISSUE TITLE
rubocop not respecting excluded files in rubocop_todo.yml

### ISSUE THREAD

**Issue by garettarrowood** [bbatsov/rubocop#5480]
## Expected behavior

The `rubocop` command to not throw offenses for files it lists under `Exclude:` in `rubocop_todo.yml`. The specific case I'm running is when I've added one excluded file into my `rubocop.yml`. 

## Actual behavior

Even though `rubocop_todo.yml` excludes files `x`, `y` and `z`, offenses are thrown when running `rubocop`.

## Steps to reproduce the problem

`rubocop.yml`
```yml
Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*'
```

After running `rubocop --auto-gen-config` on the repo, it accurately generates a `rubocop_todo.yml` containing:
```yml
Style/FrozenStringLiteralComment:
  Exclude:
    - '**/db/migrate/*'
    - 'x.rb'
    - 'y.rb'
    - 'z.rb'
```

With those files still missing a magic comment, I then run `rubocop` and receive `Style/FrozenStringLiteralComment` offenses in each of the explicitly whitelisted files.

## RuboCop version

```
0.52.1 (using Parser 2.4.0.2, running on ruby 2.3.3 x86_64-darwin15)
```
