### ISSUE TITLE
Adding magic comment (Style/FrozenStringLiteralComment) to all bin/* makes deployment fail on Heroku

### ISSUE THREAD

**Issue by strehlst** [bbatsov/rubocop#5622]
## Expected behavior

Adding frozen string literal / magic comment to offended files should not make the application undeployable on Heroku.

## Actual behavior

Running Rubocop on a fresh `Rails 5.1.5` app with the following configuration:

```
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4.3
  Exclude:
    - db/schema.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25 # Consider reducing the value to 20

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*_spec.rb
    - lib/tasks/**/*.rake
    - config/**/*.rb

Metrics/ClassLength:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/IndentHash:
  EnforcedStyle: consistent
```

I get, amongst others, this output:

```
$ rubocop
bin/bundle:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
#!/usr/bin/env ruby
^
bin/yarn:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
#!/usr/bin/env ruby
^
```

The Heroku build log states:

```
-----> Installing node-v6.11.1-linux-x64

-----> Detecting rake tasks

-----> Preparing app for Rails asset pipeline

       Running: rake assets:precompile

       ./bin/yarn: 4: ./bin/yarn: Syntax error: "(" unexpected

       Asset precompilation completed (1.47s)

       Cleaning assets

       Running: rake assets:clean
```

but **the build succeeds**.

The Heroku release log states: 

`/app/bin/bundle: 4: /app/bin/bundle: Syntax error: "(" unexpected`

and **the deployment failes**.

Removing the frozen string literal comment from `bin/yarn` and/or `bin/build` does not fix the problem.

## Steps to reproduce the problem

1. Add `# frozen_string_literal: true` to the first line of all files in bin/* (i.e. `bundle`, `rails`, `rake`, `setup`, `spring`, `update`, `yarn`) as Rubocop states an offense.
2. Make sure your Gemfile states `ruby '2.4.3'` on the second line.
3. Commit and push to your Heroku repo for deployment. No special configuration or Procfile needed.

## RuboCop version

```
$ rubocop -V
0.52.1 (using Parser 2.5.0.2, running on ruby 2.4.3 x86_64-darwin17)
```
