### ISSUE TITLE
inherit_mode Documentation Improvements

### ISSUE THREAD

**Issue by jfelchner** [bbatsov/rubocop#5640]
I'm having some major issues with the new `inherit_mode`.  Specifically around superfluous warning messages being shown that I don't care about and don't know how to get rid of.  The fact that messages are being written to the output which is not consistent with other warning or errors is also breaking build tooling which parse those messages to determine if they're warnings or errors.

What I currently have:

```yaml
# .rubocop.yml

inherit_from:
  - '.rubocop_core.yml'

Lint/HandleExceptions:
  Enabled: false
```

```yaml
# .rubocop_core.yml

Lint/HandleExceptions:
  Enabled: true
```

What I see in my output:

```
.rubocop.yml: Lint/HandleExceptions:Enabled overrides the same parameter in .rubocop_core.yml
```

I've tried changing `.rubocop.yml` to add:

```yaml
inherit_from:
  - '.rubocop_core.yml'

inherit_mode:
  override:
    - 'Enabled'

Lint/HandleExceptions:
  Enabled: false
```

I've tried both `override` and `merge` and neither of them fix the issue.

## RuboCop version

```
$ rubocop -V
0.53.0 (using Parser 2.5.0.2, running on ruby 2.4.3 x86_64-darwin16)
```

/cc @leklund

**Comment by leklund** [comment]
Those warnings come from a separate PR unrelated to the inherit_mode changes: https://github.com/bbatsov/rubocop/pull/5371 It will warn on duplicate settings regardless of `inherit_mode`

It would probably be nice to have a way to disable those warnings (cc: @jonas054) without having to disable all warnings.

**Comment by leklund** [comment]
I'm not sure what that would look like though. Changing `inherit_from` would require a lot of changes but perhaps we change `inherit_mode` to `inherit_settings`:

```
inherit_settings:
  inherit_mode:
    override:
      - 'Enabled'
  duplicate_warnings: false
```

**Comment by jfelchner** [comment]
@leklund thanks for the clarification!  @jonas054 you know I :heart: you but those warnings need to be able to be disabled. 😂

**Comment by jonas054** [comment]
@jfelchner Yes I know. :smile: I'll try to come up with something ASAP.

**Comment by jonas054** [comment]
The `inherit_mode` parameter was added to address the problem of arrays always being overridden and never merged during configuration inheritance resolution. But now we have a new problem, one that I was unaware of before; that some users want to override parameters in exactly the way that I added a warning for in #5371.

I think that the least intrusive solution would be to make it work (almost) like @jfelchner expected and let
```yaml
Lint/HandleExceptions:
  inherit_mode:
    override:
      - Enabled
```
inhibit the warning. The user has shown with this configuration that the override is intentional. This is a deviation from @leklund's original idea with `inherit_mode`, but maybe acceptable for everyone?

I also think that the warning message should direct the user to the relevant passage in the manual.

If the above solution doesn't hold water, I could just change the warning logic so that the message only appears if the `--debug/-d` option is given.
